# --- Main Colors ---
background            #111418
foreground            #e1e2e8
cursor                #e1e2e8
cursor_text_color     #111418

selection_background  #3b4858
selection_foreground  #d7e3f8

url_color             #d7bee4

# --- ANSI Colors ---
color0                #111418
color1                #ffb4ab
color2                #d7bee4
color3                #bbc7db
color4                #a0cafd
color5                #d7bee4
color6                #bbc7db
color7                #e1e2e8

color8                #43474e
color9                #93000a
color10               #523f5f
color11               #3b4858
color12               #1a4975
color13               #3b4858
color14               #523f5f
color15               #c3c6cf

# --- UI Elements ---
active_tab_foreground   #003258
active_tab_background   #a0cafd
inactive_tab_foreground #d1e4ff
inactive_tab_background #1a4975

active_border_color     #a0cafd
inactive_border_color   #8d9199

# --- Marks ---
mark1_foreground        #001d36
mark1_background        #d1e4ff
mark2_foreground        #101c2b
mark2_background        #d7e3f8
mark3_foreground        #251431
mark3_background        #f3daff