# --- Main Colors ---
background            #13140d
foreground            #e4e3d6
cursor                #e4e3d6
cursor_text_color     #13140d

selection_background  #45492f
selection_foreground  #e2e5c2

url_color             #a2d0c2

# --- ANSI Colors ---
color0                #13140d
color1                #ffb4ab
color2                #a2d0c2
color3                #c6c9a7
color4                #c1cd7d
color5                #a2d0c2
color6                #c6c9a7
color7                #e4e3d6

color8                #47483b
color9                #93000a
color10               #224e44
color11               #45492f
color12               #424b07
color13               #45492f
color14               #224e44
color15               #c8c7b7

# --- Starship Prompt Bubbles ---
color255              #424b07
color254              #c1cd7d
color253              #45492f
color252              #c6c9a7
color251              #224e44
color250              #a2d0c2
color249              #93000a
color248              #ffb4ab

color232              #ddea96
color233              #2d3400
color234              #e2e5c2
color235              #2f321a
color236              #bdecde
color237              #05372e
color238              #ffdad6
color239              #690005
color240              #ddea96

# Matched with unthemed light/dark
color243              #c1cd7d
color244              #ffb4ab
color245              #47483b

# --- UI Elements ---
active_tab_foreground   #2d3400
active_tab_background   #c1cd7d
inactive_tab_foreground #ddea96
inactive_tab_background #424b07

active_border_color     #c1cd7d
inactive_border_color   #919283

# --- Marks ---
mark1_foreground        #191e00
mark1_background        #ddea96
mark2_foreground        #1a1d07
mark2_background        #e2e5c2
mark3_foreground        #00201a
mark3_background        #bdecde