# --- Main Colors ---
background            #1a110f
foreground            #f1dfda
cursor                #f1dfda
cursor_text_color     #1a110f

selection_background  #5d4037
selection_foreground  #ffdbd1

url_color             #d9c58d

# --- ANSI Colors ---
color0                #1a110f
color1                #ffb4ab
color2                #d9c58d
color3                #e7bdb2
color4                #ffb5a0
color5                #d9c58d
color6                #e7bdb2
color7                #f1dfda

color8                #53433f
color9                #93000a
color10               #534619
color11               #5d4037
color12               #723523
color13               #5d4037
color14               #534619
color15               #d8c2bc

# --- Starship Prompt Bubbles ---
color255              #723523
color254              #ffb5a0
color253              #5d4037
color252              #e7bdb2
color251              #534619
color250              #d9c58d
color249              #93000a
color248              #ffb4ab

color232              #ffdbd1
color233              #561f0f
color234              #ffdbd1
color235              #442a22
color236              #f6e1a6
color237              #3b2f05
color238              #ffdad6
color239              #690005
color240              #ffdbd1

# Matched with unthemed light/dark
color243              #ffb5a0
color244              #ffb4ab
color245              #53433f

# --- UI Elements ---
active_tab_foreground   #561f0f
active_tab_background   #ffb5a0
inactive_tab_foreground #ffdbd1
inactive_tab_background #723523

active_border_color     #ffb5a0
inactive_border_color   #a08c87

# --- Marks ---
mark1_foreground        #3a0b01
mark1_background        #ffdbd1
mark2_foreground        #2c150f
mark2_background        #ffdbd1
mark3_foreground        #231b00
mark3_background        #f6e1a6