[config]
variant = "blackwhite"

# Wallpaper
[config.wallpaper]
set = true
command = "awww img {{ image }} --transition-type center"

# Applications
# [templates.btop]
# input_path = '~/.config/matugen/templates/btop.theme'
# output_path = '~/.config/btop/themes/matugen.theme'
# post_hook = 'pkill -USR2 btop || true'

# [templates.dunst]
# input_path = '~/.config/matugen/templates/dunstrc-colors'
# output_path = '~/.config/dunst/dunstrc'
# post_hook = 'dunstctl reload'

[templates.kitty]
input_path = '~/.config/matugen/templates/kitty-colors.conf'
output_path = '~/.config/kitty/themes/colorful.conf'
post_hook = "killall -SIGUSR1 kitty 2>/dev/null || true"

[templates.rofi]
input_path = '~/.config/matugen/templates/rofi-colors.rasi'
output_path = '~/.config/rofi/colors.rasi'

# [templates.spotify]
# input_path = '~/.config/matugen/templates/rofi-colors.rasi'
# output_path = '~/.config/spicetify/Themes/Sleek/color.ini'
# post_hook = 'spicetify watch -s 2>&1 | sed "/Reloaded Spotify/q"'

# [templates.starship]
# input_path = '~/.config/matugen/templates/starship-colors.toml'
# output_path = '~/.config/starship.toml'

# [templates.steam]
# input_path = '~/.config/matugen/templates/steam.css'
# output_path = '~/.config/AdwSteamGtk/custom.css'
# post_hook = 'adwaita-steam-gtk -i'
# # install adwsteamgtk

# [templates.waybar]
# input_path = '~/.config/matugen/templates/colors.css'
# output_path = '~/.config/waybar/colors.css'
# post_hook = "pkill -SIGUSR2 waybar"

# [templates.obs]
# input_path = 'path/to/template'
# output_path = '~/.config/obs-studio/themes/matugen.obt'

# [templates.vscode-raw]
# input_path = './templates/vscode-colors'
# output_path = '~/.cache/matugen/vscode-colors'

# [templates.vscode-json]
# input_path = './templates/vscode-colors.json'
# output_path = '~/.cache/matugen/vscode-colors.json'
# install Matugen Theme extension