$image = /home/julsen/Dotfiles/wallpaper/wallpaperflare.com_wallpaper10.jpg

$primary = rgba(a0cafdff)
$surface = rgba(111418ff)
$on_surface = rgba(e1e2e8ff)
$tertiary = rgba(d7bee4ff)
$error = rgba(ffb4abff)