# Von Pywal automatisch generierte Farbwerte für Hyprtoolkit
background = 0xFF0e0711
base = 0xFF0e0711
alternate_base = 0xFF8c8f94
text = 0xFFc8cdd4
bright_text = 0xFFc8cdd4
accent = 0xFF3192AD
accent_secondary = 0xFF5C9CAE

# === SCHRIFTARTEN ===
h1_size = 19                     # Schriftgröße für Überschriften (H1)
h2_size = 15                     # Schriftgröße für Zwischenüberschriften (H2)
h3_size = 13                     # Schriftgröße für kleine Titel (H3)
font_size = 11                   # Standard-Schriftgröße
small_font_size = 10             # Sehr kleine Textelemente
icon_theme = Adwaita             # Name des Icon-Themes (leer lassen für Systemstandard)
font_family = JetBrains Mono     # Name der Haupt-Schriftart
font_family_monospace = Monospace # Monospace-Schriftart für Mathe/Code

# === DESIGN / ABSTÄNDE ===
rounding_large = 10              # Äußere Eckenabrundung in Pixeln
rounding_small = 5               # Innere Eckenabrundung (z.B. für Buttons)
