general {
    hide_cursor = true
}

# auth {
#     pam:enabled = true
#     pam:module = "hyprlock"
#     fingerprint:enabled = false
#     fingerprint:ready_message = "(Scan fingerprint to unlock)"
#     fingerprint:present_message = "Scanning fingerprint"
#     fingerprint:retry_delay = 250
# }

background {
    monitor =
    path = ~/.config/hypr/current.wall
}

input-field {
    monitor =
    size = 250, 50
    outline_thickness = 0
    fade_on_empty = false
    font_family = "JetBrainsMono Nerd Font"
    capslock_color = rgba(216, 105, 105, 1.0)
}

label {
    monitor =
    text = $TIME
    color = rgba(200, 200, 200, 1.0)
    font_size = 55
    font_family = Noto Sans
    position = 0, 80
}