# Von Pywal automatisch generierte Farbwerte für Hyprtoolkit
background = 0xFF050505
base = 0xFF050505
alternate_base = 0xFFa8a8a8
text = 0xFFf1f1f1
bright_text = 0xFFf1f1f1
accent = 0xFFE9E9E9
accent_secondary = 0xFFF2F2F2

# === SCHRIFTARTEN ===
h1_size = 19                     # Schriftgröße für Überschriften (H1)
h2_size = 15                     # Schriftgröße für Zwischenüberschriften (H2)
h3_size = 13                     # Schriftgröße für kleine Titel (H3)
font_size = 11                   # Standard-Schriftgröße
small_font_size = 10             # Sehr kleine Textelemente
icon_theme = Adwaita             # Name des Icon-Themes (leer lassen für Systemstandard)
font_family = JetBrains Mono     # Name der Haupt-Schriftart
font_family_monospace = Monospace # Monospace-Schriftart für Mathe/Code

# === DESIGN / ABSTÄNDE ===
rounding_large = 10              # Äußere Eckenabrundung in Pixeln
rounding_small = 5               # Innere Eckenabrundung (z.B. für Buttons)
