screencopy {
    # default setup https://wiki.hypr.land/Hypr-Ecosystem/xdg-desktop-portal-hyprland/#category-screencopy
    max_fps = 120
    allow_token_by_default = false
    custom_picker_binary = "custom_picker_binary"
    force_shm = false
}